### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by Mostafa-shenawy** [oktadeveloper/okta-php-core-rest-api-example#1]
First I start php server via ssh console => https://snag.gy/BHUmbe.jpg
Then When I send request using postman I get 404 not found error => https://snag.gy/ur2EUZ.jpg

Do you have any idea about how can I fix this?

**Comment by Endymion1977** [comment]
You should call the code using localhost or 127.0.0.1 (port 8000) as that's where you start the PHP web server - do not use a public IP address as in the Postman screenshot. This is a response from an Apache Web server and not the built-in PHP server (apparently you have a Web server running on this IP address).
