### ISSUE TITLE
test API endpoints using Postman

### ISSUE THREAD

**Issue by knot22** [oktadeveloper/okta-php-core-rest-api-example#2]
This is an excellent example; however, I'm having difficulty understanding how to test the API endpoints using Postman.

Part of the tutorial says this:
"We’ll create a /public/index.php file to serve as our front controller and process the requests, and a src/Controller/PersonController.php to handle the API endpoints (called from the front controller after validating the URI)."

So PersonController is instantiated in public/index.php - that makes sense.  But how does one go about testing the endpoints using Postman given that PersonController is a class and Postman must be provided with a URL?

**Comment by Endymion1977** [comment]
Hi,

If the base URL is http://127.0.0.1:8000, then you need to send the following requests in Postman to test the different endpoints:

// return all records
GET http://127.0.0.1:8000/person

// return a specific record
GET http://127.0.0.1:8000/person/{id}

// create a new record
POST http://127.0.0.1:8000/person

// update an existing record
PUT http://127.0.0.1:8000/person/{id}

// delete an existing record
DELETE http://127.0.0.1:8000/person/{id}

For the POST and PUT requests, you need to send the request body like this in Postman:

- set the Body type to: raw
- set the Content Type to: JSON (application/json) 
- paste the payload in JSON format

There is also a simple command-line client implementation at the end of the article, which demonstrates calling the GET endpoints using Curl.

Let me know if this works for you, or if you have any other questions.

**Comment by knot22** [comment]
Thank-you for the response.  It seems I'm stuck on the base URL part.  I'm running Apache as the web server using XAMPP on a Windows 10 machine.  So localhost:80 works in the browser - it points to C:\xampp\htdocs.  Also, localhost:8080 works - it is setup as a virtual host that points to PHP files on an external storage device.  The okta-php-core-rest-api-example was cloned to a location on the external storage device.  Should it have been cloned to a location on C: to get the URLs to work?  If so, what location?

http://127.0.0.1:8000 results in "This site can't be reached" in the browser.

**Comment by Endymion1977** [comment]
OK, in that case you should use localhost:8080 as the base URL. Can you try to load http://localhost:8080/person in the browser and see if you'll get a JSON response with the list of people? You can try GET requests directly in the browser, but POST/PUT/DELETE are trickier so Postman is recommended.

**Comment by knot22** [comment]
Thank-you for the guidance on what to use as the base URL.
The browser can see the index of the project when using localhost:8080/git as the base URL -
![IndexOf_git_okta-php-core-rest-api-example](https://user-images.githubusercontent.com/20587751/66212956-7258bb00-e684-11e9-85bb-bfdadadcc8c4.PNG)
Note that okta-php-core-rest-api-example is stored within a folder called git in the localhost:8080 location.

However, the GET request for the list of people in the browser is giving a 404 error -
![GET_git_okta-php-core-rest-api-example_person](https://user-images.githubusercontent.com/20587751/66212974-7b498c80-e684-11e9-97c5-805b7004e882.PNG)

Why would this be?

**Comment by Endymion1977** [comment]
I see, you should point the virtual host to the /public directory - the rest of the directories should not be web-accessible. The way it's set up now, try to access http://localhost:8080/public/person instead and see if that works.

**Comment by knot22** [comment]
OK, I tried a couple different things and got these responses -
![GET_git-okta-php-core-rest-api-example_public_person_attempt1](https://user-images.githubusercontent.com/20587751/66237539-e746e780-e6ba-11e9-90ea-80281871c62c.png)
![GET_git-okta-php-core-rest-api-example_public_person_attempt2](https://user-images.githubusercontent.com/20587751/66237545-e910ab00-e6ba-11e9-9dcb-6e630175b0e7.png)

I did some looking in the public/index.php file and see that PersonController is instantiated there and calls processRequest(), which makes sense.  I also checked to make sure 'api_user'@'localhost' has access to the api_example database and that looks good, I think.
![GrantsForAPI_user](https://user-images.githubusercontent.com/20587751/66237810-a3081700-e6bb-11e9-81d6-5a6e921bd8b0.png)

Not sure why it is still giving the 404 error after including /public/ in the URL.  Do you have some other thoughts as to why it can't find the page?

**Comment by knot22** [comment]
I've made some progress by disabling part of the code in index.php.  Here is the temporarily modified file:
![ModifiedIndex](https://user-images.githubusercontent.com/20587751/66247502-ee81eb80-e6e2-11e9-8886-38020bfc2da2.png)
And here is what the browser displays:
![BrowserResultOfIndexPage](https://user-images.githubusercontent.com/20587751/66247520-13765e80-e6e3-11e9-9271-ae1d3fce9375.PNG)
It appears that storing the project in a folder deeper than originally intended causes problems  when checking if the endpoint starts with /person and extracting the user ID from the URI.  However, I expected http://localhost:8080/git/okta-php-core-rest-api-example/public/person to work correctly when the index.php file was modified as shown above, but it does not.  It still gives a 404 error.

Is there code that maps http://localhost:8080/git/okta-php-core-rest-api-example/public/person to http://localhost:8080/git/okta-php-core-rest-api-example/public/index.php?  I'm lost as to where the app is supposed to go given the http://localhost:8080/git/okta-php-core-rest-api-example/public/person URI.  There doesn't appear to be a .htaccess file, or something similar, to map public/person to public/index.php (if that is what's supposed to happen).

**Comment by Endymion1977** [comment]
Yes, the example assumes that /public would be the virtual host directory and all URLs will be routed to public/index.php (but /public won't be a part of the URL). You can modify the code to strip a starting '/public' from the URI before parsing it, you can try to run the project through the built-in PHP server as the article shows (instead of using XAMPP), or you can set up a virtual host pointed to /public and call the code through the virtual host. All of these solutions should work.

**Comment by stefanvz** [comment]
experiencing the same issue while testing with MAMP or on my web environment.

With starting php -S localhost:8000 -t public from my installation directory $uri[1] is blank. adding  /person to localhost:8000 everything works as intended, $uri[1] = person.

With the MAMP / Web environment the $uri[1] is blank as well, but adding /person to the api.example.com just resolves in 404 Not Found because the directory /person does not exist.

Can this simply be solved with a RewriteRule?

PS: enjoying the tutorial very much btw, thanks a lot!

**Comment by stefanvz** [comment]
solved it for me with TDD and a final .htaccess file in the root folder of the app that redirects non-existing requests to the index.php in /public

RewriteEngine on 
RewriteBase / 
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteRule ^(.*)$ index.php [NC,L]

depending on the depth of the PHP_URL_PATH one has to adapt the $uri[n] for userId and redirecting if-clause in index.php

hope this helps.

**Comment by knot22** [comment]
Thank-you for the explanation of options - using the built-in PHP server or setting up a virtual host.  I opted to try the built-in PHP server and was able to get it to work.  I was unaware that there was such a thing as a built-in PHP server so this line near the bottom of the tutorial 
![image](https://user-images.githubusercontent.com/20587751/66531678-341f2980-ead2-11e9-8f1b-cd8bc55f4b40.png)
didn't have any meaning until I did some Googling about using the built-in PHP server.

Anyhow, all 5 Postman requests are working now.  Here are the specifics, in case anyone else can make use of this info:
![GitBash_OktaAPIexample_2019-10-09](https://user-images.githubusercontent.com/20587751/66531559-cb37b180-ead1-11e9-81d6-921350d83621.PNG)

Here is an example of the Postman request that gets all people:
![image](https://user-images.githubusercontent.com/20587751/66531585-ec989d80-ead1-11e9-8b07-ab75e7ad8226.png)

I used `0.0.0.0:8000` instead of `127.0.0.1:8000` initially because the okta example is stored on an external device and this post [https://www.sitepoint.com/taking-advantage-of-phps-built-in-server/](url) contained the following info:
![image](https://user-images.githubusercontent.com/20587751/66532161-f91df580-ead3-11e9-8d7a-2e8a6b02eb46.png)

However, I later tried `127.0.0.1:8000` and it works equally as well as `0.0.0.0:8000`.
