### ISSUE TITLE
Missing validation of user input against sql injection

### ISSUE THREAD

**Issue by GabrieleMartini** [oktadeveloper/okta-php-core-rest-api-example#5]
Validation on user input, while creating and inserting new person, is limited to checking the fields are set: watch out for sql injection! (And for storing passwords in plain text).

**Comment by aaronpk** [comment]
This project uses prepared statements to avoid SQL injection. This project also does not store passwords at all, it uses Okta for managing user accounts instead.

If you have a specific example of a possible case of SQL injection or this project storing passwords please let us know.
